stages:
  data_download:
    cmd: python laod_date.py
    deps:
      - config.yaml
    outs:
      - /content/lb3

  train:
    cmd: python train.py
    deps:
      - /content/lb3
      - config.yaml
      - train.py
    outs:
      - model.pth
      - logs/training.log

  evaluate:
    cmd: python evaluate.py
    deps:
      - model.pth
      - data/
      - config.yaml
      - evaluate.py
    metrics:
      - metrics.json
