stages:
  load_date:
    cmd: python load_date.py
    params:
      - data
    deps:
      - params.yaml
      - load_date.py
    outs:
      - data/102flower

  train:
    cmd: python train.py
    params:
      - training.epoch
      - training.batch_size
      - training.optimizer
      - model
      - logging
      - artifacts
    deps:
      - data/102flower
      - params.yaml
      - train.py
    outs:
      - artifacts/model.pth
      - logs/training.log

  evaluate:
    cmd: python evaluate.py
    params:
      - evaluation.metrics
      - artifacts.output_dir
    deps:
      - artifacts/model.pth
      - data/102flower
      - params.yaml
      - evaluate.py
    metrics:
      - metrics.json
