stages:
  load_date:
    cmd: python load_date.py
    deps:
      - config.yaml
      - load_date.py
    outs:
      - data/102flower

  train:
    cmd: python train.py
    deps:
      - data/102flower
      - config.yaml
      - train.py
    outs:
      - model.pth
      - logs/training.log

  evaluate:
    cmd: python evaluate.py
    deps:
      - model.pth
      - data/102flower
      - config.yaml
      - evaluate.py
    metrics:
      - metrics.json
